[build]
  command = "hugo --gc --minify --themesDir ../../"
  base    = "exampleSite"
  publish = "public"

[build.environment]
  HUGO_BASEURL        = "https://color-your-world-demo.netlify.app"
  HUGO_THEME          = "repo"
  HUGO_VERSION        = "0.77.0"
  HUGO_ENABLEGITINFO  = "true"
